# YAML file in the release branch

#trigger:
#- main
schedules:
- cron: "40 20 * * Mon,Wed,Fri"
  displayName: Stop cluster at 8 pm (Monday-Friday)
#  branches:
#    include:
#    - main
  always: true  
resources:
- repo: self

variables:
- group: EPlast

stages:
- stage: Stop
  displayName: Stop stage
  jobs:  
  - job: Stop
    displayName: Stop
    pool:
      vmImage: 'ubuntu-latest'
    steps:     
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          timedatectl
          'az aks stop --name $(name) --resource-group $(name)'
