# YAML file in the release branch

trigger:
- main
schedules:
- cron: "50 15 * * 1-5"
  displayName: Daily build at midnight (Monday-Friday)
  branches:
    include:
    - main
resources:
- repo: self

variables:
- group: EPlast

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:     
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az account list'