# YAML file in the release branch

trigger:
- main
schedules:
- cron: "0 7 * * 1-5"
  displayName: Start cluster at 10 am (Monday-Friday)
  branches:
    include:
    - main
  always: true    
resources:
- repo: self

variables:
- group: EPlast

stages:
- stage: Start
  displayName: Start stage
  jobs:  
  - job: Start
    displayName: Start
    pool:
      vmImage: 'ubuntu-latest'
    steps:   
    - task: CmdLine@2
      displayName: Set system Timezone to IST
      inputs:
        script: |
          sudo timedatectl
          
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az aks start --name $(name) --resource-group $(name)'
