# YAML file in the release branch

trigger:
- main
schedules:
- cron: "0 20 * * 1-5"
  displayName: Start cluster at 10 am (Monday-Friday)
  branches:
    include:
    - main
resources:
- repo: self

variables:
- group: EPlast

stages:
- stage: Stop
  displayName: Stop stage
  jobs:  
  - job: Stop
    displayName: Stop
    pool:
      vmImage: 'ubuntu-latest'
    steps:     
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az aks stop --name $(name) --resource-group $(name)'
